language: go
go: 1.11.x
go_import_path: github.com/lopezator/nexmo-go

os: linux
dist: xenial

env:
  - GO111MODULE=on

before_script:
  - go get -u -t ./...

script:
  - make prepare
  - make sanity-check
  - make test

cache:
  directories:
    - $GOPATH/pkg
